---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001 #check using "id username" in SSH
      - PGID=100 #check using "id username" in SSH
      - TZ=Asia/Riyadh
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/bazarr/config:/config
      - /link/to/media/movies:/movies #optional
      - /link/to/media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
