---
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: my-dashboard
    environment:
      - PUID=1001 #check using "id username" in SSH
      - PGID=100 #check using "id username" in SSH
      - TZ=Asia/Riyadh

    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/dashy/config:/app/user-data #using CHANGE_TO_COMPOSE_DATA_PATH will work automatically if you setup docker compose correctly
    ports:
      - 4000:8080
    restart: unless-stopped
