---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Riyadh
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/nextcloud/config:/config
      - /link/to/nextcloud_data:/data
    ports:
      - 443:443
    restart: unless-stopped
