---
services:
    portainer-ce:
        ports:
            - '8000:8000'
            - '9443:9443'
        container_name: portainer
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'CHANGE_TO_COMPOSE_DATA_PATH/portainer/portainer_data:/data'  #using CHANGE_TO_COMPOSE_DATA_PATH will work automatically if you setup docker compose correctly
        image: 'portainer/portainer-ce:latest'
