---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Riyadh
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/radarr/data:/config
      - /link/to/media/movies:/movies #optional
      - /link/to/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
