---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Riyadh
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/sonarr/data:/config
      - /link/to/media/tv:/tv #optional
      - /link/to/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
