---
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: mysyncthing #optional
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Riyadh
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/syncthing/config:/config
      - /srv/dev-disk-by-uuid-d6852fc3-0a9e-4744-b04b-3a8b323559d7/syncthing:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    network_mode: host
