version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - proxy
    ports:
      - "4000:3000" # Updated port mapping
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  proxy:
    external: true
