version: '3.8'
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - proxy
    volumes:
      - loki-data:/etc/loki
    ports:
      - "3100:3100" # Loki's internal port remains the same, no conflict

volumes:
  loki-data:

networks:
  proxy:
    external: true
